$path = "c:\d\bluuu\bluuu\src\home1.jsx"
$text = [IO.File]::ReadAllText($path)

$text = $text -replace 'max-w-\[1400px\]', 'max-w-7xl'
$text = $text -replace 'max-w-\[1240px\]', 'max-w-6xl'
$text = $text -replace 'max-w-\[1200px\]', 'max-w-6xl'
$text = $text -replace 'max-w-\[900px\]', 'max-w-4xl'
$text = $text -replace 'min-h-\[100dvh\]', 'min-h-screen'
$text = $text -replace 'h-\[100dvh\]', 'min-h-screen'
$text = $text -replace 'min-h-\[750px\]', ''
$text = $text -replace 'min-h-\[460px\]', 'min-h-96'
$text = $text -replace 'min-w-\[750px\]', 'min-w-fit'
$text = $text -replace 'h-\[240px\]', 'h-64'
$text = $text -replace 'h-\[500px\]', 'min-h-96'
$text = $text -replace 'h-\[560px\]', 'min-h-[36rem]'
$text = $text -replace 'text-\[10px\]', 'text-xs'
$text = $text -replace 'text-\[11px\]', 'text-xs'
$text = $text -replace 'text-\[12px\]', 'text-xs'
$text = $text -replace 'text-\[13px\]', 'text-sm'
$text = $text -replace 'text-\[14px\]', 'text-sm'
$text = $text -replace 'text-\[15px\]', 'text-sm'
$text = $text -replace 'text-\[16px\]', 'text-base'
$text = $text -replace 'text-\[17px\]', 'text-base'
$text = $text -replace 'text-\[18px\]', 'text-lg'
$text = $text -replace 'text-\[19px\]', 'text-xl'
$text = $text -replace 'text-\[20px\]', 'text-xl'
$text = $text -replace 'text-\[22px\]', 'text-xl'
$text = $text -replace 'text-\[24px\]', 'text-2xl'
$text = $text -replace 'text-\[26px\]', 'text-3xl'
$text = $text -replace 'text-\[28px\]', 'text-3xl'
$text = $text -replace 'text-\[32px\]', 'text-4xl'
$text = $text -replace 'text-\[34px\]', 'text-4xl'
$text = $text -replace 'text-\[36px\]', 'text-4xl'
$text = $text -replace 'text-\[40px\]', 'text-5xl'
$text = $text -replace 'text-\[48px\]', 'text-5xl'
$text = $text -replace 'text-\[56px\]', 'text-6xl'
$text = $text -replace 'text-\[100px\]', 'text-8xl'

$text = $text -replace 'leading-\[1\.05\]', 'leading-none'
$text = $text -replace 'leading-\[1\.4\]', 'leading-snug'
$text = $text -replace 'leading-\[1\.6\]', 'leading-relaxed'
$text = $text -replace 'tracking-\[0\.2em\]', 'tracking-widest'
$text = $text -replace 'tracking-\[0\.3em\]', 'tracking-widest'
$text = $text -replace 'tracking-\[0\.15em\]', 'tracking-wider'
$text = $text -replace 'tracking-\[0\.05em\]', 'tracking-wide'

$text = $text -replace 'w-\[1px\]', 'w-px'
$text = $text -replace 'w-\[14px\]', 'w-3.5'
$text = $text -replace 'w-\[18px\]', 'w-5'
$text = $text -replace 'w-\[20px\]', 'w-5'
$text = $text -replace 'h-\[14px\]', 'h-3.5'
$text = $text -replace 'h-\[18px\]', 'h-5'
$text = $text -replace 'h-\[20px\]', 'h-5'
$text = $text -replace 'w-\[25%\]', 'w-1/4'
$text = $text -replace 'w-\[85%\]', 'w-10/12'

$text = $text -replace '-my-\[50px\]', '-my-12'
$text = $text -replace 'py-\[50px\]', 'py-12'
$text = $text -replace 'pt-\[120px\]', 'pt-32'
$text = $text -replace 'py-\[18px\]', 'py-4'
$text = $text -replace 'gap-\[4px\]', 'gap-1'

$text = $text -replace 'flex-\[0_0_85%\]', 'flex-none w-10/12'
$text = $text -replace 'aspect-\[4/3\]', 'aspect-video'

$text = $text -replace 'scale-\[1\.02\]', 'scale-100'
$text = $text -replace 'scale-\[1\.03\]', 'scale-105'
$text = $text -replace 'scale-\[1\.04\]', 'scale-105'
$text = $text -replace 'scale-\[1\.05\]', 'scale-105'
$text = $text -replace 'brightness-\[0\.7\]', 'brightness-75'

$text = $text -replace 'bg-\[#FF6B4A\]', 'bg-orange-500'
$text = $text -replace 'bg-\[#FDF8F4\]', 'bg-orange-50'
$text = $text -replace 'bg-\[#F0C966\]', 'bg-yellow-400'
$text = $text -replace 'border-\[#F0E6DD\]', 'border-orange-200'
$text = $text -replace 'text-\[#FF6B4A\]', 'text-orange-500'
$text = $text -replace 'fill-\[#FF6B4A\]', 'fill-orange-500'
$text = $text -replace 'border-\[3px\]', 'border-4'
$text = $text -replace 'border-\[2px\]', 'border-2'

$text = $text -replace 'bg-white/\[0\.0[1-3]\]', 'bg-white/5'
$text = $text -replace 'bg-white/\[0\.0[4-9]\]', 'bg-white/10'
$text = $text -replace 'bg-white/\[0\.10\]', 'bg-white/10'

$text = $text -replace 'shadow-\[0_20px_60px_rgba\(0,37,66,0\.08\)\]', 'shadow-xl'
$text = $text -replace 'shadow-\[0_25px_70px_rgba\(0,37,66,0\.12\)\]', 'shadow-2xl'
$text = $text -replace 'shadow-\[0_8px_30px_rgba\(0,115,224,0\.3\)\]', 'shadow-xl shadow-primary-500/30'
$text = $text -replace 'shadow-\[0_0_50px_rgba\(0,115,224,0\.15\)\]', 'shadow-2xl shadow-primary-500/20'
$text = $text -replace 'shadow-\[0_20px_40px_rgba\(0,37,66,0\.1\)\]', 'shadow-xl'

$text = $text -replace 'border-t border-white/5 relative z-10 selection:bg-primary-400/20', 'relative z-10 selection:bg-primary-400/20'

[IO.File]::WriteAllText($path, $text)
Write-Output "Done"
