/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      backgroundImage: {
        "hero-premium":
          "radial-gradient(120% 80% at 20% 0%, rgba(255,255,255,0.92) 0%, rgba(245,249,252,0.72) 40%, rgba(232,240,247,0.95) 100%)",
        "sky-glow":
          "radial-gradient(80% 60% at 20% 0%, var(--primary-50) 0%, transparent 70%), radial-gradient(65% 55% at 90% 90%, var(--primary-50) 0%, transparent 72%)",
        "sky-glow-warm":
          "radial-gradient(120% 120% at 10% 0%, var(--primary-50) 0%, transparent 55%), linear-gradient(180deg, var(--neutral-100) 0%, var(--neutral-50) 100%)",
      },
      boxShadow: {
        sm: "none",
        DEFAULT: "none",
        md: "none",
        lg: "none",
        xl: "none",
        "2xl": "none",
        inner: "none",
        none: "none",
        card: "var(--shadow-card)",
        floating: "var(--shadow-floating)",
      },
      colors: {
        primary: {
          50: "#E6F4FF",
          100: "#CCE9FF",
          200: "#99D3FF",
          300: "#66BDFF",
          400: "#339FFF",
          500: "#007FFF",
          505: "#007FFF",
          600: "#0073E0",
          700: "#005CB3",
          800: "#004786",
          900: "#003459",
          950: "#002542",
        },
        secondary: {
          50: "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#cbd5e1",
          400: "#94a3b8",
          500: "#64748b",
          600: "#475569",
          700: "#334155",
          800: "#1e293b",
          900: "#0f172a",
          950: "#020617",
        },
        neutral: {
          50: "#FAFBFB",
          100: "#F3F5F6",
          200: "#E6EAEC",
          300: "#D9DFE2",
          400: "#CBD4D8",
          500: "#BEC9CF",
          600: "#B1BDC6",
          700: "#99A5AE",
          800: "#7F8A95",
          900: "#607077",
          950: "#4B575F",
        },
        /* Theme tokens (CSS variables from server) */
        "accent-soft": "var(--accent-soft)",
        "accent-soft-strong": "var(--accent-soft-strong)",
        "accent-strong": "var(--accent-strong)",
        "t-bg": "var(--bg)",
        "bg-gradient-start": "var(--bg-gradient-start)",
        "bg-gradient-mid": "var(--bg-gradient-mid)",
        "bg-gradient-end": "var(--bg-gradient-end)",
        "border-soft": "var(--border-soft)",
        "border-strong": "var(--border-strong)",
        "t-border": "var(--border)",
        "t-danger": "var(--danger)",
        "t-link": "var(--link)",
        "link-hover": "var(--link-hover)",
        "t-overlay": "var(--overlay)",
        "overlay-soft": "var(--overlay-soft)",
        "overlay-strong": "var(--overlay-strong)",
        "premium-border": "var(--premium-border)",
        "premium-soft": "var(--premium-soft)",
        "premium-text": "var(--premium-text)",
        "t-success": "var(--success)",
        "t-surface": "var(--surface)",
        "surface-glass": "var(--surface-glass)",
        "surface-glass-strong": "var(--surface-glass-strong)",
        "surface-muted": "var(--surface-muted)",
        "surface-soft": "var(--surface-soft)",
        "text-faint": "var(--text-faint)",
        "text-ghost": "var(--text-ghost)",
        "text-inverse": "var(--text-inverse)",
        "text-inverse-faint": "var(--text-inverse-faint)",
        "text-inverse-muted": "var(--text-inverse-muted)",
        success: "#10b981",
        danger: "#ef4444",
        warning: "#f59e0b",
      },
      letterSpacing: {
        "wide-xs": "0.1em",
        "wide-sm": "0.12em",
        "wide-md": "0.15em",
        "wide-lg": "0.18em",
        "wide-xl": "0.2em",
        "wide-2xl": "0.24em",
        "wide-3xl": "0.26em",
        "wide-4xl": "0.3em",
      },
      maxWidth: {
        "screen-xl": "1280px",
      },
      fontFamily: {
        body: [
          "var(--font-body)",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "Arial",
          "sans-serif",
        ],
        heading: [
          "var(--font-heading)",
          "var(--font-body)",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "Arial",
          "sans-serif",
        ],
      },
    },
  },
  plugins: [],
}
